In [49]:
import pandas as pd
from konlpy.tag import Okt
from kiwipiepy import Kiwi
import re
from emoji import core
import emoji

okt = Okt()
kiwi = Kiwi()

In [50]:
df = pd.read_csv(
    "./data/Youtube_comment_01/raw/youtube_comments_NEWS_01.csv",
    index_col=False 
)

df.head()

,동영상 제목,채널명,댓글 유형,작성자,댓글 내용,좋아요,작성일시,대댓글 수,댓글 ID,동영상 ID,작성자 채널 ID,수정일시,상위 댓글 ID,감성
0,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,최상위 댓글,@suroogarlieara,얔ㅋㅋㅋㅋㅋㅋㅌㅋㅋㅋㅋ 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아...,19839,2025-04-28T16:51:31Z,34,UgyEnpeXdwIa5NSRi714AaABAg,qOB5sIujPH8,UC_wT1ZdL5eGssgiwf_cfnqA,2025-04-28T16:51:31Z,NaN,중립
1,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@dddongni,저 트윗쓴사람 플레이브팬아님 ㅠ 조롱할려고 쓴 글임,458,2025-04-29T10:53:51Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVHvITEHoU,qOB5sIujPH8,UCUiy_juTyQxcsDCUBUqwtNQ,2025-04-29T10:53:51Z,UgyEnpeXdwIa5NSRi714AaABAg,중립
2,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@서현-l5d9m,​@dddongni 헐.. 솔직히 전 플레이브 응원해요 힘내세요. 다들 플레이브한테...,117,2025-04-29T11:35:24Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVMffXbAVP,qOB5sIujPH8,UCA8NjllW2H9PoUDa0b5NYuA,2025-04-29T11:35:39Z,UgyEnpeXdwIa5NSRi714AaABAg,긍정
3,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@이쥬-j1b,@서현-l5d9m 플레이브팬들이 타팬덤들 후려쳐서 케이팝 팬덤들 공공의 적이 되어버...,406,2025-04-29T13:41:15Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVa4Pzt_bL,qOB5sIujPH8,UCvXnUGHnZB61v1RGm_ox1zg,2025-04-29T13:41:15Z,UgyEnpeXdwIa5NSRi714AaABAg,중립
4,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@조수현-f5x,아니 버츄얼 아이돌이 왜 플레이브라는 듣보잡임? 이세돌이나 스텔라이브가 근본인데 어...,14,2025-04-29T14:19:28Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVeSLSNGS1,qOB5sIujPH8,UCbcRkR8dH-tN_fdbgjjrSMw,2025-04-29T14:19:28Z,UgyEnpeXdwIa5NSRi714AaABAg,중립

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5474 entries, 0 to 5473
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   동영상 제목     5474 non-null   str
 1   채널명        5474 non-null   str
 2   댓글 유형      5474 non-null   str
 3   작성자        5474 non-null   str
 4   댓글 내용      5474 non-null   str
 5   좋아요        5474 non-null   int64
 6   작성일시       5474 non-null   str
 7   대댓글 수      5474 non-null   int64
 8   댓글 ID      5474 non-null   str
 9   동영상 ID     5474 non-null   str
 10  작성자 채널 ID  5474 non-null   str
 11  수정일시       5474 non-null   str
 12  상위 댓글 ID   2111 non-null   str
 13  감성         5474 non-null   str
dtypes: int64(2), str(12)
memory usage: 598.8 KB

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5474 entries, 0 to 5473
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   동영상 제목     5474 non-null   str
 1   채널명        5474 non-null   str
 2   댓글 유형      5474 non-null   str
 3   작성자        5474 non-null   str
 4   댓글 내용      5474 non-null   str
 5   좋아요        5474 non-null   int64
 6   작성일시       5474 non-null   str
 7   대댓글 수      5474 non-null   int64
 8   댓글 ID      5474 non-null   str
 9   동영상 ID     5474 non-null   str
 10  작성자 채널 ID  5474 non-null   str
 11  수정일시       5474 non-null   str
 12  상위 댓글 ID   2111 non-null   str
 13  감성         5474 non-null   str
dtypes: int64(2), str(12)
memory usage: 598.8 KB

# 2. 데이터 전처리

In [53]:
df = df.drop_duplicates(subset=["댓글 내용"])

## 1) datetime 열 생성

In [54]:
df["datetime"] = pd.to_datetime(df["작성일시"], format="%Y-%m-%dT%H:%M:%SZ")

In [55]:
print(df["datetime"].dtypes)

datetime64[us]

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 5280 entries, 0 to 5473
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   동영상 제목     5280 non-null   str
 1   채널명        5280 non-null   str
 2   댓글 유형      5280 non-null   str
 3   작성자        5280 non-null   str
 4   댓글 내용      5280 non-null   str
 5   좋아요        5280 non-null   int64
 6   작성일시       5280 non-null   str
 7   대댓글 수      5280 non-null   int64
 8   댓글 ID      5280 non-null   str
 9   동영상 ID     5280 non-null   str
 10  작성자 채널 ID  5280 non-null   str
 11  수정일시       5280 non-null   str
 12  상위 댓글 ID   2037 non-null   str
 13  감성         5280 non-null   str
 14  datetime   5280 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(2), str(12)
memory usage: 660.0 KB

## 2) 결측치 처리

In [57]:
df.isna().sum()

동영상 제목          0
채널명             0
댓글 유형           0
작성자             0
댓글 내용           0
좋아요             0
작성일시            0
대댓글 수           0
댓글 ID           0
동영상 ID          0
작성자 채널 ID       0
수정일시            0
상위 댓글 ID     3243
감성              0
datetime        0
dtype: int64

In [58]:
null_comments = df[df['상위 댓글 ID'].isnull()]
print(null_comments.head())

                                         동영상 제목          채널명   댓글 유형  \
0   인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127  케이팝 읽어주는 남녀  최상위 댓글
6   인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127  케이팝 읽어주는 남녀  최상위 댓글
12  인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127  케이팝 읽어주는 남녀  최상위 댓글
18  인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127  케이팝 읽어주는 남녀  최상위 댓글
24  인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127  케이팝 읽어주는 남녀  최상위 댓글

                 작성자                                              댓글 내용  \
0    @suroogarlieara  얔ㅋㅋㅋㅋㅋㅋㅌㅋㅋㅋㅋ 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아...
6         @LOl-kb3ty           자기들이 재밌자고 올린 것 같은데 그걸 진짜 받아줘서 기절함ㅋㅋㅋㅋㅋㅋㅋ
12  @user-pv4ke5ni7u  광야에 있는 어떤 오빠는 순간이동도도 하고 물도 다룬다야ㅋㅋㅋ 어떤 언냐는 로켓펀처...
18             @해리피터  에스파는 하늘 날아다니는건 기본이고 발사도 함 ㅋㅋㅋㅋㅋㅋㅋㅋ\nSM은 진심 하늘 ...
24              @비머v       뭘 좋아하든간에 그냥 자기가 좋아하는사람들 응원하고 서로 예의 지키면서 살면 됨

      좋아요                  작성일시  대댓글 수                       댓글 ID  \
0   19839  2025-04-28T16:51:31Z     34  UgyEnpeXdwIa5NSRi714AaABAg
6   12601  2025-04-29T08:28:16Z     19  Ugwrlk6PiA1tNpZoDtZ4AaABAg
12   7015  2025-04-29T00:56:27Z     12  UgwOLTF3341Uo-lm7tZ4AaABAg
18   3246  2025-04-29T02:34:45Z     14  UgzVWXrDwSMjGSbwDLt4AaABAg
24   1755  2025-04-29T16:44:24Z     32  UgzXCD0claE783i50aB4AaABAg

         동영상 ID                 작성자 채널 ID                  수정일시 상위 댓글 ID  감성  \
0   qOB5sIujPH8  UC_wT1ZdL5eGssgiwf_cfnqA  2025-04-28T16:51:31Z      NaN  중립
6   qOB5sIujPH8  UC8M3Z85Zx-FbaeAx9BhQacg  2025-04-29T08:28:16Z      NaN  긍정
12  qOB5sIujPH8  UCOMUQyP1jRqi10mUy2Tzing  2025-04-29T00:56:27Z      NaN  중립
18  qOB5sIujPH8  UC3_7LHIEAy_f5H-r1HP_bXA  2025-04-29T02:35:28Z      NaN  중립
24  qOB5sIujPH8  UCt8QBnXarkC_TUklMoSDJTA  2025-04-29T16:44:24Z      NaN  긍정

              datetime
0  2025-04-28 16:51:31
6  2025-04-29 08:28:16
12 2025-04-29 00:56:27
18 2025-04-29 02:34:45
24 2025-04-29 16:44:24

In [59]:
df_new = df.fillna("none").reset_index(drop=True)
df_new.isna().sum()

동영상 제목       0
채널명          0
댓글 유형        0
작성자          0
댓글 내용        0
좋아요          0
작성일시         0
대댓글 수        0
댓글 ID        0
동영상 ID       0
작성자 채널 ID    0
수정일시         0
상위 댓글 ID     0
감성           0
datetime     0
dtype: int64

In [60]:
df_new

,동영상 제목,채널명,댓글 유형,작성자,댓글 내용,좋아요,작성일시,대댓글 수,댓글 ID,동영상 ID,작성자 채널 ID,수정일시,상위 댓글 ID,감성,datetime
0,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,최상위 댓글,@suroogarlieara,얔ㅋㅋㅋㅋㅋㅋㅌㅋㅋㅋㅋ 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아...,19839,2025-04-28T16:51:31Z,34,UgyEnpeXdwIa5NSRi714AaABAg,qOB5sIujPH8,UC_wT1ZdL5eGssgiwf_cfnqA,2025-04-28T16:51:31Z,none,중립,2025-04-28 16:51:31
1,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@dddongni,저 트윗쓴사람 플레이브팬아님 ㅠ 조롱할려고 쓴 글임,458,2025-04-29T10:53:51Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVHvITEHoU,qOB5sIujPH8,UCUiy_juTyQxcsDCUBUqwtNQ,2025-04-29T10:53:51Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 10:53:51
2,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@서현-l5d9m,​@dddongni 헐.. 솔직히 전 플레이브 응원해요 힘내세요. 다들 플레이브한테...,117,2025-04-29T11:35:24Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVMffXbAVP,qOB5sIujPH8,UCA8NjllW2H9PoUDa0b5NYuA,2025-04-29T11:35:39Z,UgyEnpeXdwIa5NSRi714AaABAg,긍정,2025-04-29 11:35:24
3,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@이쥬-j1b,@서현-l5d9m 플레이브팬들이 타팬덤들 후려쳐서 케이팝 팬덤들 공공의 적이 되어버...,406,2025-04-29T13:41:15Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVa4Pzt_bL,qOB5sIujPH8,UCvXnUGHnZB61v1RGm_ox1zg,2025-04-29T13:41:15Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 13:41:15
4,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@조수현-f5x,아니 버츄얼 아이돌이 왜 플레이브라는 듣보잡임? 이세돌이나 스텔라이브가 근본인데 어...,14,2025-04-29T14:19:28Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVeSLSNGS1,qOB5sIujPH8,UCbcRkR8dH-tN_fdbgjjrSMw,2025-04-29T14:19:28Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 14:19:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,버추얼 아이돌 인기가 이정도? '이세계 아이돌' 역대 펀딩 88억 돌파/ KNN,KNN NEWS,대댓글,@개입신당,2030 이세돌\n1020 스텔,0,2025-06-29T12:33:13Z,0,UgxeFaxVDEXwxSD6XR14AaABAg.AExfh3AZmyMAJxXmXUAjNH,Av1zma6uJco,UCVacEr4NSuuz7-AW4U6s8rw,2025-06-29T12:33:13Z,UgxeFaxVDEXwxSD6XR14AaABAg,중립,2025-06-29 12:33:13
5276,버추얼 아이돌 인기가 이정도? '이세계 아이돌' 역대 펀딩 88억 돌파/ KNN,KNN NEWS,최상위 댓글,@쿠찌모찌,저걸로 동덕여대 54억 지원해주면 되겠네,0,2024-11-27T18:35:44Z,0,UgwM7qvWZEP49pR7HeB4AaABAg,Av1zma6uJco,UCzUYjIa0TKA5j9xrhTyhdow,2024-11-27T18:35:44Z,none,중립,2024-11-27 18:35:44
5277,버추얼 아이돌 인기가 이정도? '이세계 아이돌' 역대 펀딩 88억 돌파/ KNN,KNN NEWS,최상위 댓글,@수진-o9o,으 싫어,2,2025-01-26T09:19:11Z,2,Ugxcsxy9oxVskKZvKDR4AaABAg,Av1zma6uJco,UC8bXvdaVue00LHoK4kGkDew,2025-01-26T09:19:11Z,none,부정,2025-01-26 09:19:11
5278,버추얼 아이돌 인기가 이정도? '이세계 아이돌' 역대 펀딩 88억 돌파/ KNN,KNN NEWS,대댓글,@유석엄마파워,오우 닭 한대 치시고,1,2025-02-15T02:08:46Z,0,Ugxcsxy9oxVskKZvKDR4AaABAg.ADke9__ZPTxAEYNnfKNHve,Av1zma6uJco,UCOuHRA_LMeGxJEkUI_zJIVg,2025-02-15T02:08:46Z,Ugxcsxy9oxVskKZvKDR4AaABAg,중립,2025-02-15 02:08:46
5279,버추얼 아이돌 인기가 이정도? '이세계 아이돌' 역대 펀딩 88억 돌파/ KNN,KNN NEWS,대댓글,@아리가또라베스크-i6p,난 너가 좋단다 품어,1,2025-02-21T14:17:16Z,0,Ugxcsxy9oxVskKZvKDR4AaABAg.ADke9__ZPTxAEo7wdHVad7,Av1zma6uJco,UCzS_BQ9EvOQo90TnV2POsRg,2025-02-21T14:17:16Z,Ugxcsxy9oxVskKZvKDR4AaABAg,중립,2025-02-21 14:17:16

## 3) 클리닝

In [61]:
cleaned_comments = []

for comment in df_new["댓글 내용"]:
    if pd.isna(comment) or not isinstance(comment, str):
        cleaned_comments.append("")
        continue
    
    # 1. 이모지(그림 문자) 제거
    text = core.replace_emoji(comment,"")
    
    # 2. 한글과 공백만 남기기 (초성 'ㅋㅋㅋ', 영어, 숫자, 특수문자 모두 제거)
    text = re.sub(r'[^가-힣\s]', '', text)
    
    # 3. 불필요한 연속 공백 제거 및 양쪽 끝 공백 제거
    text = re.sub(r'\s+', ' ', text).strip()
    
    cleaned_comments.append(text)

In [62]:
df_new['cleaned_comment'] = cleaned_comments

In [63]:
print(df_new[['cleaned_comment']])

                                        cleaned_comment
0                 얔 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아준겈
1                            저 트윗쓴사람 플레이브팬아님 조롱할려고 쓴 글임
2     헐 솔직히 전 플레이브 응원해요 힘내세요 다들 플레이브한테 욕많이 하시던데 팬분들 한테도
3     서현 플레이브팬들이 타팬덤들 후려쳐서 케이팝 팬덤들 공공의 적이 되어버림 업보여서 ...
4     아니 버츄얼 아이돌이 왜 플레이브라는 듣보잡임 이세돌이나 스텔라이브가 근본인데 어디...
...                                                 ...
5275                                             이세돌 스텔
5276                               저걸로 동덕여대 억 지원해주면 되겠네
5277                                               으 싫어
5278                                        오우 닭 한대 치시고
5279                                        난 너가 좋단다 품어

[5280 rows x 1 columns]

In [64]:
df_new.head()

,동영상 제목,채널명,댓글 유형,작성자,댓글 내용,좋아요,작성일시,대댓글 수,댓글 ID,동영상 ID,작성자 채널 ID,수정일시,상위 댓글 ID,감성,datetime,cleaned_comment
0,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,최상위 댓글,@suroogarlieara,얔ㅋㅋㅋㅋㅋㅋㅌㅋㅋㅋㅋ 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아...,19839,2025-04-28T16:51:31Z,34,UgyEnpeXdwIa5NSRi714AaABAg,qOB5sIujPH8,UC_wT1ZdL5eGssgiwf_cfnqA,2025-04-28T16:51:31Z,none,중립,2025-04-28 16:51:31,얔 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아준겈
1,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@dddongni,저 트윗쓴사람 플레이브팬아님 ㅠ 조롱할려고 쓴 글임,458,2025-04-29T10:53:51Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVHvITEHoU,qOB5sIujPH8,UCUiy_juTyQxcsDCUBUqwtNQ,2025-04-29T10:53:51Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 10:53:51,저 트윗쓴사람 플레이브팬아님 조롱할려고 쓴 글임
2,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@서현-l5d9m,​@dddongni 헐.. 솔직히 전 플레이브 응원해요 힘내세요. 다들 플레이브한테...,117,2025-04-29T11:35:24Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVMffXbAVP,qOB5sIujPH8,UCA8NjllW2H9PoUDa0b5NYuA,2025-04-29T11:35:39Z,UgyEnpeXdwIa5NSRi714AaABAg,긍정,2025-04-29 11:35:24,헐 솔직히 전 플레이브 응원해요 힘내세요 다들 플레이브한테 욕많이 하시던데 팬분들 한테도
3,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@이쥬-j1b,@서현-l5d9m 플레이브팬들이 타팬덤들 후려쳐서 케이팝 팬덤들 공공의 적이 되어버...,406,2025-04-29T13:41:15Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVa4Pzt_bL,qOB5sIujPH8,UCvXnUGHnZB61v1RGm_ox1zg,2025-04-29T13:41:15Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 13:41:15,서현 플레이브팬들이 타팬덤들 후려쳐서 케이팝 팬덤들 공공의 적이 되어버림 업보여서 ...
4,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@조수현-f5x,아니 버츄얼 아이돌이 왜 플레이브라는 듣보잡임? 이세돌이나 스텔라이브가 근본인데 어...,14,2025-04-29T14:19:28Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVeSLSNGS1,qOB5sIujPH8,UCbcRkR8dH-tN_fdbgjjrSMw,2025-04-29T14:19:28Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 14:19:28,아니 버츄얼 아이돌이 왜 플레이브라는 듣보잡임 이세돌이나 스텔라이브가 근본인데 어디...

In [65]:
df_new = df_new.drop(columns=["댓글 내용"])

In [66]:
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 5280 entries, 0 to 5279
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   동영상 제목           5280 non-null   str
 1   채널명              5280 non-null   str
 2   댓글 유형            5280 non-null   str
 3   작성자              5280 non-null   str
 4   좋아요              5280 non-null   int64
 5   작성일시             5280 non-null   str
 6   대댓글 수            5280 non-null   int64
 7   댓글 ID            5280 non-null   str
 8   동영상 ID           5280 non-null   str
 9   작성자 채널 ID        5280 non-null   str
 10  수정일시             5280 non-null   str
 11  상위 댓글 ID         5280 non-null   str
 12  감성               5280 non-null   str
 13  datetime         5280 non-null   datetime64[us]
 14  cleaned_comment  5280 non-null   str
dtypes: datetime64[us](1), int64(2), str(12)
memory usage: 618.9 KB

In [67]:
df_new.to_csv(
    "./data/Youtube_comment_01/raw/processed/youtube_comments_clean.csv"
)

In [68]:
df2 = pd.read_csv(
    "./data/Youtube_comment_01/raw/processed/youtube_comments_clean.csv",
    index_col=0,
    keep_default_na=False
)
df2.head(2)

,동영상 제목,채널명,댓글 유형,작성자,좋아요,작성일시,대댓글 수,댓글 ID,동영상 ID,작성자 채널 ID,수정일시,상위 댓글 ID,감성,datetime,cleaned_comment
0,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,최상위 댓글,@suroogarlieara,19839,2025-04-28T16:51:31Z,34,UgyEnpeXdwIa5NSRi714AaABAg,qOB5sIujPH8,UC_wT1ZdL5eGssgiwf_cfnqA,2025-04-28T16:51:31Z,none,중립,2025-04-28 16:51:31,얔 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아준겈
1,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@dddongni,458,2025-04-29T10:53:51Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVHvITEHoU,qOB5sIujPH8,UCUiy_juTyQxcsDCUBUqwtNQ,2025-04-29T10:53:51Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 10:53:51,저 트윗쓴사람 플레이브팬아님 조롱할려고 쓴 글임

In [69]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5280 entries, 0 to 5279
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   동영상 제목           5280 non-null   str
 1   채널명              5280 non-null   str
 2   댓글 유형            5280 non-null   str
 3   작성자              5280 non-null   str
 4   좋아요              5280 non-null   int64
 5   작성일시             5280 non-null   str
 6   대댓글 수            5280 non-null   int64
 7   댓글 ID            5280 non-null   str
 8   동영상 ID           5280 non-null   str
 9   작성자 채널 ID        5280 non-null   str
 10  수정일시             5280 non-null   str
 11  상위 댓글 ID         5280 non-null   str
 12  감성               5280 non-null   str
 13  datetime         5280 non-null   str
 14  cleaned_comment  5280 non-null   str
dtypes: int64(2), str(13)
memory usage: 618.9 KB

# 3. 데이터 탐색

In [70]:
df2["동영상 제목"].unique()

<StringArray>
[          '인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127',
                                          '버츄얼 아이돌 소신발언',
 '노래 잘하는 외계인? 음악방송 1위 하는 버추얼 아이돌 (2024.09.27/뉴스데스크/MBC)',
             '콘서트 티켓 8분 만에 전석 매진시킨다는 버추얼 아이돌 근황 / 스브스뉴스',
          '버추얼 아이돌 인기가 이정도? '이세계 아이돌' 역대 펀딩 88억 돌파/ KNN']
Length: 5, dtype: str

# 4. 토크나이징

## 1) 전체 데이터

In [71]:
df2.head()

,동영상 제목,채널명,댓글 유형,작성자,좋아요,작성일시,대댓글 수,댓글 ID,동영상 ID,작성자 채널 ID,수정일시,상위 댓글 ID,감성,datetime,cleaned_comment
0,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,최상위 댓글,@suroogarlieara,19839,2025-04-28T16:51:31Z,34,UgyEnpeXdwIa5NSRi714AaABAg,qOB5sIujPH8,UC_wT1ZdL5eGssgiwf_cfnqA,2025-04-28T16:51:31Z,none,중립,2025-04-28 16:51:31,얔 던지는것도 웃기려고 하는거엿겠지만 저건 받아치는쪽이 잘 받아준겈
1,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@dddongni,458,2025-04-29T10:53:51Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVHvITEHoU,qOB5sIujPH8,UCUiy_juTyQxcsDCUBUqwtNQ,2025-04-29T10:53:51Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 10:53:51,저 트윗쓴사람 플레이브팬아님 조롱할려고 쓴 글임
2,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@서현-l5d9m,117,2025-04-29T11:35:24Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVMffXbAVP,qOB5sIujPH8,UCA8NjllW2H9PoUDa0b5NYuA,2025-04-29T11:35:39Z,UgyEnpeXdwIa5NSRi714AaABAg,긍정,2025-04-29 11:35:24,헐 솔직히 전 플레이브 응원해요 힘내세요 다들 플레이브한테 욕많이 하시던데 팬분들 한테도
3,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@이쥬-j1b,406,2025-04-29T13:41:15Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVa4Pzt_bL,qOB5sIujPH8,UCvXnUGHnZB61v1RGm_ox1zg,2025-04-29T13:41:15Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 13:41:15,서현 플레이브팬들이 타팬덤들 후려쳐서 케이팝 팬덤들 공공의 적이 되어버림 업보여서 ...
4,인간 아이돌(엔시티) VS 버츄얼아이돌(플레이브)#엔시티#플레이브#엔시티127,케이팝 읽어주는 남녀,대댓글,@조수현-f5x,14,2025-04-29T14:19:28Z,0,UgyEnpeXdwIa5NSRi714AaABAg.AHTM32k7weKAHVeSLSNGS1,qOB5sIujPH8,UCbcRkR8dH-tN_fdbgjjrSMw,2025-04-29T14:19:28Z,UgyEnpeXdwIa5NSRi714AaABAg,중립,2025-04-29 14:19:28,아니 버츄얼 아이돌이 왜 플레이브라는 듣보잡임 이세돌이나 스텔라이브가 근본인데 어디...

#### 명사+형용사

In [72]:
stopwords = [
    "저건", "받아준겈", "글임", "아님", "레이브", "브라", "이세돌", "같은데", "그냥",
    "철컹", "있음", "이런", "존나", "심지어", "나로", "혹시", "그러는데", "혹시",
    "숭숭", "우리", "이건", "늬긔", "더라도", "누가", "힐거", "아뵹키", "아닠", "엔시", "지네",
    "기네", "엔시", "그로", "여기", "우리", "근까", "절대", "있지", "아니", "병신", "이어도", 
    "뻔했냐고", "그냥", "느그", "쬬쬬쬬쬬쬬쬬", "신동", "김신영", "이란", "어어", "입니다", "플리",
    "허버허버", "드릉드릉", "잠수", "스폰지밥", "스펀지밥", "세계", "적금", "한남", "오우", "어디가",
    "남혐", "광대", "얼굴", "보성", "깃치", "준비", "깊다", "마을", "네모", "이파리", "플리", "세계",
    "아이돌"

]

sentence_words = []
sentence_index = []

for _, row in df2.iterrows():                           # 1. 데이터프레임의 행을 하나씩 반복하며 꺼냄
    sent = row["cleaned_comment"]                       # 2. 분석할 댓글 원문 추출
    comment_id = row["동영상 ID"]                        # 3. 댓글과 연결된 비디오 ID(인덱스) 저장

    if pd.isna(sent):
        sentence_words.append(None)                     # 4. 빈 댓글(NaN)인 경우 처리
        sentence_index.append(comment_id)               # 5. 결과 리스트에 빈 값 추가 후 다음으로 넘어감
        continue

    clean_sent = re.sub("[^a-zA-Z가-힣\s]", "", sent)   # 6. 특수문자/숫자 제거(한글, 영어, 공백만 남김)

    # 🔹 norm=True, stem=True 추가 (핵심)
    result = okt.pos(clean_sent, norm=True, stem=True)                        # 7. 형태소 분석기를 이용해 품사 태깅 수행

    keywords = []
    for word, pos in result:
        if pos in ["Noun", "Adjective"] and len(word) > 1:           # 8. 명사(Noun)이면서 길이가 2자 이상이고
            if word in stopwords:                       # 9. 미리 정의한 불용어(stopwords)에
                continue
            keywords.append(word)                          # 10. 포함되지 않는 단어만 리스트로 생성

    # 👉 핵심: 한 문장 단위
    sentence_words.append(keywords if keywords else None)
    sentence_index.append(comment_id)

In [73]:
sentence_series = pd.Series(
    sentence_words,
    index=sentence_index,
    name="keywords"
)

In [74]:
sentence_series.head()

qOB5sIujPH8                                     None
qOB5sIujPH8                        [트윗, 사람, 아니다, 조롱]
qOB5sIujPH8                               [솔직하다, 응원]
qOB5sIujPH8            [서현, 팬덤, 케이팝, 팬덤, 공공, 업보, 없다]
qOB5sIujPH8    [아니다, 버츄얼, 플레이, 듣보잡, 스텔라, 이브, 근본, 근본]
Name: keywords, dtype: object

In [75]:
sentence_series.value_counts()

keywords
[킹애]                         25
[진짜]                         18
[화이팅]                        18
[모두]                         18
[사랑]                         16
                             ..
[아니다, 초반, 서나, 유행, 후반, 좋다]     1
[기준, 조용하다, 자쇼]                1
[스텔]                          1
[동덕여대, 지원]                    1
[싫다]                          1
Name: count, Length: 4304, dtype: int64

In [76]:
sentence_series.to_csv("./data/youtube_comment_01/raw/subsets/youtube_comments_N_A.csv")